# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geradorQR.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(303, 176)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_gera = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gera.setGeometry(QtCore.QRect(100, 110, 91, 23))
        self.btn_gera.setObjectName("btn_gera")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 40, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("IMG_20210126_180939_441-removebg-preview.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label.setObjectName("label")
        self.txt_link = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_link.setGeometry(QtCore.QRect(20, 40, 211, 20))
        self.txt_link.setObjectName("txt_link")
        self.txt_nome_arquvo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nome_arquvo.setGeometry(QtCore.QRect(20, 80, 211, 20))
        self.txt_nome_arquvo.setObjectName("txt_nome_arquvo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 91, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QrCode Francine"))
        self.btn_gera.setText(_translate("MainWindow", "Gerar QRCode"))
        self.label.setText(_translate("MainWindow", "Insira Seu Link"))
        self.label_3.setText(_translate("MainWindow", "Nome Do arquivo"))
